echo Fetching Package...
wget -O discord.deb "https://discordapp.com/api/download?platform=linux&format=deb" -q
echo Building Package...
sudo dpkg -i discord.deb &> /dev/null
rm discord.deb &> /dev/null
