echo Fetching Package...
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -q
echo Building Package...
sudo dpkg -i ./google-chrome-stable_current_amd64.deb &> /dev/null
rm google-chrome-stable_current_amd64.deb &> /dev/null