echo Fetching Package...
curl https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.3.00.5153_amd64.deb --output teams.deb -s
echo Building Package...
sudo dpkg -i teams.deb &> /dev/null
rm teams.deb
