echo Fetching Package...
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
chmod +x Miniconda3-latest-Linux-x86_64.sh &> /dev/null
echo Running Installer...
./Miniconda3-latest-Linux-x86_64.sh
echo Cleaning... 
rm Miniconda3-latest-Linux-x86_64.sh 
